name: wallet
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10
  shared_preferences: ^2.3.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  connectivity_plus: ^6.0.3
  change_app_package_name: ^1.1.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  pinput: ^4.0.0
  mask_text_input_formatter: ^2.9.0
  carousel_slider: ^4.2.1
  lottie: ^3.1.1
  url_launcher: ^6.2.6
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  easy_localization: ^3.0.7
  dio: ^5.5.0+1
  get_it: ^7.7.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf